# backend/alembic/script.py.mako
"""Add file and pgvector document chunks

Revision ID: 39151ffbd604
Revises: 0001
Create Date: 2026-09-04 11:00:46.149187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39151ffbd604'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_event_records_event_type'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_occurred_at'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_task_id'), table_name='event_records')
    op.drop_table('event_records')
    op.drop_table('artifacts')
    op.add_column('document_chunks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=True)
    op.drop_constraint(op.f('document_chunks_file_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'files', ['file_id'], ['id'], ondelete='CASCADE')
    op.add_column('files', sa.Column('file_path', sa.String(), nullable=False))
    op.add_column('files', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('files_project_id_fkey'), 'files', type_='foreignkey')
    op.create_foreign_key(None, 'files', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('files', 'uploaded_at')
    op.drop_column('files', 'storage_path')
    op.drop_column('files', 'deleted_at')
    op.drop_column('files', 'size_bytes')
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('projects', 'deleted_at')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('tasks_retry_of_task_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'retry_of_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('retry_of_task_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_retry_of_task_id_fkey'), 'tasks', 'tasks', ['retry_of_task_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
    op.add_column('projects', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('projects', 'updated_at')
    op.add_column('files', sa.Column('size_bytes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('files', sa.Column('storage_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('files', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.create_foreign_key(op.f('files_project_id_fkey'), 'files', 'projects', ['project_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('files', 'created_at')
    op.drop_column('files', 'file_path')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_file_id_fkey'), 'document_chunks', 'files', ['file_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('document_chunks', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
               nullable=False)
    op.drop_column('document_chunks', 'created_at')
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('agent_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('artifact_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content_ref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('artifacts_agent_run_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('artifacts_task_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('artifacts_pkey'))
    )
    op.create_table('event_records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('agent_run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('correlation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('causation_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('schema_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('event_records_pkey'))
    )
    op.create_index(op.f('ix_event_records_task_id'), 'event_records', ['task_id'], unique=False)
    op.create_index(op.f('ix_event_records_occurred_at'), 'event_records', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_event_records_event_type'), 'event_records', ['event_type'], unique=False)
    op.drop_table('events')
    # ### end Alembic commands ###