# backend/alembic/script.py.mako
"""Add AuditLogs table

Revision ID: 8a95d0c87b4f
Revises: 39151ffbd604
Create Date: 2026-09-04 11:35:52.299834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a95d0c87b4f'
down_revision: Union[str, None] = '39151ffbd604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###