# backend/alembic/script.py.mako
"""transactional_outbox_and_leases

Revision ID: 9eeb6c3f39f3
Revises: 0274bd4b551c
Create Date: 2026-09-06 06:31:26.876724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eeb6c3f39f3'
down_revision: Union[str, None] = '0274bd4b551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stream_name', sa.String(), nullable=False),
    sa.Column('event_payload', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_outbox_events_processed', 'outbox_events', ['processed'], unique=False)
    op.drop_table('model_registry')
    op.add_column('agent_runs', sa.Column('failure_reason', sa.String(), nullable=True))
    op.alter_column('agent_runs', 'tier_used',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
    op.drop_constraint(op.f('agent_runs_task_id_fkey'), 'agent_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_runs', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_column('agent_runs', 'iteration_count')
    op.add_column('plan_steps', sa.Column('step_number', sa.Integer(), nullable=False))
    op.add_column('plan_steps', sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('plan_steps', sa.Column('retryable', sa.Boolean(), nullable=True))
    op.add_column('plan_steps', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('plan_steps_agent_run_id_fkey'), 'plan_steps', type_='foreignkey')
    op.create_foreign_key(None, 'plan_steps', 'agent_runs', ['agent_run_id'], ['id'], ondelete='CASCADE')
    op.drop_column('plan_steps', 'result')
    op.drop_column('plan_steps', 'step_index')
    op.drop_column('plan_steps', 'args')
    op.add_column('tasks', sa.Column('retry_of_task_id', sa.UUID(), nullable=True))
    op.add_column('tasks', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('heartbeat', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('lease_expiry', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('attempt_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'tasks', ['retry_of_task_id'], ['id'], ondelete='SET NULL')
    op.add_column('tool_executions', sa.Column('result', sa.String(), nullable=True))
    op.add_column('tool_executions', sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('tool_executions_plan_step_id_fkey'), 'tool_executions', type_='foreignkey')
    op.create_foreign_key(None, 'tool_executions', 'plan_steps', ['plan_step_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tool_executions', 'tool_name')
    op.drop_column('tool_executions', 'error_message')
    op.drop_column('tool_executions', 'completed_at')
    op.drop_column('tool_executions', 'duration_ms')
    op.drop_column('tool_executions', 'started_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_executions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('tool_executions', sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('tool_executions', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('tool_executions', sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tool_executions', sa.Column('tool_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'tool_executions', type_='foreignkey')
    op.create_foreign_key(op.f('tool_executions_plan_step_id_fkey'), 'tool_executions', 'plan_steps', ['plan_step_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tool_executions', 'executed_at')
    op.drop_column('tool_executions', 'result')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'attempt_count')
    op.drop_column('tasks', 'lease_expiry')
    op.drop_column('tasks', 'heartbeat')
    op.drop_column('tasks', 'started_at')
    op.drop_column('tasks', 'worker_id')
    op.drop_column('tasks', 'retry_of_task_id')
    op.add_column('plan_steps', sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('plan_steps', sa.Column('step_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('plan_steps', sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'plan_steps', type_='foreignkey')
    op.create_foreign_key(op.f('plan_steps_agent_run_id_fkey'), 'plan_steps', 'agent_runs', ['agent_run_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('plan_steps', 'created_at')
    op.drop_column('plan_steps', 'retryable')
    op.drop_column('plan_steps', 'tool_args')
    op.drop_column('plan_steps', 'step_number')
    op.add_column('agent_runs', sa.Column('iteration_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'agent_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_runs_task_id_fkey'), 'agent_runs', 'tasks', ['task_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('agent_runs', 'tier_used',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.drop_column('agent_runs', 'failure_reason')
    op.create_table('model_registry',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tier', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('model_tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('model_registry_pkey'))
    )
    op.drop_index('ix_outbox_events_processed', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###