# backend/alembic/script.py.mako
"""Add ResourceMetric table

Revision ID: d42e9d7e0f21
Revises: 8a95d0c87b4f
Create Date: 2026-09-04 11:45:33.951652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42e9d7e0f21'
down_revision: Union[str, None] = '8a95d0c87b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_metrics', sa.Column('memory_percent', sa.Float(), nullable=False))
    op.add_column('resource_metrics', sa.Column('active_tasks', sa.Integer(), nullable=False))
    op.add_column('resource_metrics', sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('resource_metrics', 'active_task_count')
    op.drop_column('resource_metrics', 'sampled_at')
    op.drop_column('resource_metrics', 'vram_used_mb')
    op.drop_column('resource_metrics', 'ram_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_metrics', sa.Column('ram_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('resource_metrics', sa.Column('vram_used_mb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('resource_metrics', sa.Column('sampled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('resource_metrics', sa.Column('active_task_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('resource_metrics', 'recorded_at')
    op.drop_column('resource_metrics', 'active_tasks')
    op.drop_column('resource_metrics', 'memory_percent')
    # ### end Alembic commands ###